Converting the data to encoded array is very crucial, because the dimensionality difference between the arrays can make model prone to input errors

**Some Common Terms to remember**
1) Corpus
2) Vocabulary
3) Document
4) Word

Two Techniques Usually 
1) Bag of Words(BOW)
2) One Hot Encoding
3) TFIDF
4) WORD2VEC
5) TRANSFORMERS

In [1]:
import numpy as np
import pandas as pd

In [2]:
sentences = [
    "I love programming and coding programming.",
    "Python is a versatile language programming.",
    "Machine learning is fascinating to explore.",
    "Data science is the future ahead.",
    "Artificial intelligence is a evolving rapidly.",
    "Coding challenges improve with problem-solving skills.",
    "Natural language processing is a subfield.",
    "Deep learning requires large datasets PAD.",
    "Visualization makes data insights clearer PAD.",
    "Algorithms form the backbone of science."
]

In [3]:
df = pd.DataFrame({'text':sentences,'output':[1,1,1,1,1,0,0,0,0,0]})
df

text  output
0         I love programming and coding programming.       1
1        Python is a versatile language programming.       1
2        Machine learning is fascinating to explore.       1
3                  Data science is the future ahead.       1
4     Artificial intelligence is a evolving rapidly.       1
5  Coding challenges improve with problem-solving...       0
6         Natural language processing is a subfield.       0
7         Deep learning requires large datasets PAD.       0
8     Visualization makes data insights clearer PAD.       0
9           Algorithms form the backbone of science.       0

{'love': 23, 'programming': 31, 'and': 2, 'coding': 7, 'python': 32, 'is': 19, 'versatile': 41, 'language': 20, 'machine': 24, 'learning': 22, 'fascinating': 13, 'to': 40, 'explore': 12, 'data': 8, 'science': 35, 'the': 39, 'future': 15, 'ahead': 0, 'artificial': 3, 'intelligence': 18, 'evolving': 11, 'rapidly': 33, 'challenges': 5, 'improve': 16, 'with': 43, 'problem': 29, 'solving': 37, 'skills': 36, 'natural': 26, 'processing': 30, 'subfield': 38, 'deep': 10, 'requires': 34, 'large': 21, 'datasets': 9, 'pad': 28, 'visualization': 42, 'makes': 25, 'insights': 17, 'clearer': 6, 'algorithms': 1, 'form': 14, 'backbone': 4, 'of': 27}

Through Count Vectorizer works technique, A number is assigned to every word, for every sentence an array has length of number of unique words in a vector, in that vector values are filled up, let's say programming, which has value of 31 and "I love programming and coding programming" this sentence has "programming" word two times.
this is the sentences vector
[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Now at 31st place the value is "2"
The Place of "Programming" in the vector is "31" and it occurs two times so value is "2".
print([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0][31])


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
bow.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 

In [7]:
print(cv.vocabulary_)

{'love': 23, 'programming': 31, 'and': 2, 'coding': 7, 'python': 32, 'is': 19, 'versatile': 41, 'language': 20, 'machine': 24, 'learning': 22, 'fascinating': 13, 'to': 40, 'explore': 12, 'data': 8, 'science': 35, 'the': 39, 'future': 15, 'ahead': 0, 'artificial': 3, 'intelligence': 18, 'evolving': 11, 'rapidly': 33, 'challenges': 5, 'improve': 16, 'with': 43, 'problem': 29, 'solving': 37, 'skills': 36, 'natural': 26, 'processing': 30, 'subfield': 38, 'deep': 10, 'requires': 34, 'large': 21, 'datasets': 9, 'pad': 28, 'visualization': 42, 'makes': 25, 'insights': 17, 'clearer': 6, 'algorithms': 1, 'form': 14, 'backbone': 4, 'of': 27}


**Add TF-IDF Here**

**Word2Vec**

**Word2Vec** is a popular technique in Natural Language Processing (NLP) to represent words as numerical vectors in a high-dimensional space. ***It captures the semantic meaning of words based on their context within a corpus of text.***

### Key Concepts of Word2Vec
1. **Word Embedding**: Words are represented as dense, fixed-length vectors (e.g., 100-dimensional or 300-dimensional vectors). Words with similar meanings are placed closer together in the vector space.

2. **Contextual Learning**: Word2Vec leverages the context in which words appear to learn their representations. For example, "king" and "queen" might appear in similar contexts, so their vectors will be close to each other.

3. **Models**:
   Word2Vec has two main training architectures:
   - **Continuous Bag of Words (CBOW)**:
     - Predicts a target word based on the surrounding context words.
     - Focuses on learning from the average of context word vectors.
   - **Skip-gram**:
     - Predicts context words based on a target word.
     - Particularly effective for smaller datasets and capturing rare words.

4. **Training Objective**: Word2Vec uses neural networks to optimize the embeddings. It maximizes the likelihood that words appearing in similar contexts have similar vectors.

### Example
Consider the sentence: *"The cat sat on the mat."*
- In CBOW, the model might predict the word "sat" based on the context words "The," "cat," "on," and "the."
- In Skip-gram, the model might predict the words "The," "cat," "on," and "the" based on the word "sat."

### Properties of Word2Vec
1. **Semantic Similarity**:
   - Words with similar meanings are placed closer together in the embedding space.
   - Example: `cosine_similarity(vector('king'), vector('queen'))` will be high.

2. **Word Analogies**:
   - Word2Vec embeddings allow solving analogies like:
     - "king" - "man" + "woman" ≈ "queen"

3. **Dimensionality Reduction**:
   - Instead of one-hot encoding (where each word is a large, sparse vector), Word2Vec creates dense vectors of fixed dimensions, making them computationally efficient.

### Implementation
Word2Vec is implemented in libraries like:
- **Gensim** (Python): Easy-to-use for training and using pre-trained embeddings.
- **TensorFlow** and **PyTorch**: For customized embeddings.

#### Using Pre-trained Models
Pre-trained embeddings like **Google's Word2Vec** or **GloVe** are often used in practice to save time and leverage large-scale datasets.

### Advantages
- Captures semantic relationships between words.
- Reduces dimensionality, making models more efficient.
- Improves NLP tasks like text classification, sentiment analysis, and machine translation.

### Limitations
- Cannot handle out-of-vocabulary (OOV) words directly.
- Requires a significant amount of data to generate quality embeddings.
- Ignores the internal structure of words (e.g., morphology), which newer methods like FastText address.

In [8]:
%pip install --upgrade gensim --user

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import gensim

In [10]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk

In [11]:
nltk.download('punkt')
# Download the punkt tokenizer data to the specified directory
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ahmed\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ahmed\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [12]:

# Open file and read content
with open("gameofthronesbooksdataset/001ssb.txt", "r", encoding="utf-8") as f:
    corpus = f.read()

# Tokenize the corpus into sentences and preprocess
story = [simple_preprocess(sent) for sent in sent_tokenize(corpus)]

In [13]:
print(story[0])
print(story[1])

['game', 'of', 'thrones', 'book', 'one', 'of', 'song', 'of', 'ice', 'and', 'fire', 'by', 'george', 'martin', 'prologue', 'we', 'should', 'start', 'back', 'gared', 'urged', 'as', 'the', 'woods', 'began', 'to', 'grow', 'dark', 'around', 'them']
['the', 'wildlings', 'are', 'dead']


In [14]:
len(story)

27244

In [15]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    
)

In [16]:
model.build_vocab(story)

In [17]:
model.train(story,total_examples=model.corpus_count,epochs = model.epochs)

(1058206, 1423500)

In [18]:
model.wv.most_similar('jon')

[('sansa', 0.9812719821929932),
 ('bran', 0.9782366156578064),
 ('catelyn', 0.9767033457756042),
 ('he', 0.9698653817176819),
 ('arya', 0.9668296575546265),
 ('ned', 0.957272469997406),
 ('robb', 0.954663872718811),
 ('loss', 0.9333587288856506),
 ('she', 0.9215131402015686),
 ('dany', 0.919743001461029)]

In [19]:
model.wv.similarity('jon','bastard')

0.76026416

In [20]:
#Cannot handle out-of-vocabulary (OOV) words directly.
#model.wv.similarity('john','bastard')

In [21]:
model.wv['deep'].shape

(100,)

In [22]:
vec = model.wv.get_normed_vectors()


In [23]:
vec.shape

(7432, 100)

In [24]:
y = model.wv.index_to_key

In [25]:
vec

array([[-0.02605041,  0.02918113, -0.01200826, ..., -0.16625279,
         0.00774373,  0.12309115],
       [-0.01610404,  0.1142247 ,  0.00513151, ..., -0.17945386,
         0.03556407,  0.03219678],
       [-0.1706722 ,  0.04649099,  0.03768931, ..., -0.0279575 ,
         0.05561876, -0.11462245],
       ...,
       [-0.07449918, -0.04743175,  0.04847319, ..., -0.14783564,
         0.0476921 , -0.06953512],
       [ 0.00764005,  0.05178713,  0.01782185, ..., -0.17530124,
        -0.00418918, -0.01470289],
       [ 0.01918257,  0.11844984, -0.0007703 , ..., -0.19881171,
         0.03938087, -0.03205011]], dtype=float32)

In [26]:
from sklearn.decomposition import PCA
#

In [27]:
pca = PCA(n_components=3)
# n_components defines the vector dimensions.

In [28]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [29]:
X

array([[-0.34183878,  0.15522283,  0.36864063],
       [-0.41560537,  0.04045856,  0.22929956],
       [ 0.3812499 ,  0.10898286, -0.0177125 ],
       ...,
       [ 0.22573002,  0.06241977, -0.23165324],
       [-0.25828993, -0.05783111,  0.05217224],
       [-0.22164695, -0.01595664, -0.02519912]], dtype=float32)

In [30]:
%pip install plotly
%pip install nbformat>=4.2.0

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2,color = y[200:300])
fig.show()